### ISSUE TITLE
Retrieving RNA raw counts

### ISSUE THREAD

**Issue by seoyeonoh12** [satijalab/azimuth#100]
I have questions from ref.Rds file to retrieve RNA count data. 

When I would like to retrieve count data by
data <- GetAssayData(object = pbmc, slot = "data")
It returns matrix of all zeroes. 

And there are 2 assays available: refAssay and ADT. 
ADT data seems to be available. However, refAssay does not contain any non-zeroes. Is this just an empty matrix? 

How can I extract RNA count matrix, not ADT?

Thank you.

**Comment by andrewwbutler** [comment]
Hi,

By design, these Azimuth references contain only the minimal information needed to carry out the mapping procedure (and so the RNA counts have been removed). If you want to access the raw underlying data, the reference information pages link back to the original publication(s) where you can find the data. For PBMC reference, this data can be found [here](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE164378).
