### ISSUE TITLE
GEO link: Azimuth Bone Marrow

### ISSUE THREAD

**Issue by EST09** [satijalab/azimuth#117]
Hi, 

I was wondering if there was a GEO link for the azimuth bone marrow dataset please? I was hoping to use the detailed annotations for bridge integration.

I've downloaded it from [Zenodo](https://zenodo.org/record/5521512#.YwY0xC0w30o) and via url (https://seurat.nygenome.org/azimuth/references/v1.0.0/human_bonemarrow) from Issue (#99) but both seem to have the expression removed. 

I saw the previous issue for PBMC (#98) and saw that the solution was to download via GEO but couldn't manage to find the link. 

Thank you!

Best wishes, 
Emily

**Comment by AustinHartman** [comment]
Hi - as you've discovered the Azimuth references available on Zenodo do not store raw counts information since they're not required for mapping query datasets and can consume a bunch of memory. The references are often constructed from different starting points (GEO links, Seurat objects, human cell atlas downloads, etc) so while the PBMC reference can be reconstructed from a GEO link it's a bit different for bone marrow. The [azimuth-references](https://github.com/satijalab/azimuth-references/tree/master) repo provides snakemake workflows to reproduce each of the available references, which you could use to generate the full bone marrow dataset. Or if you send me an email (ahartman@nygenome.org) I can send you a link to download the full reference.

**Comment by EST09** [comment]
Hi Austin, 

Thank you for your quick reply and help! I'll email you and give snakemake a try in the meantime. 

Thanks again, 
Emily
