### ISSUE TITLE
Missing gene expression data of `bonemarrowref`

### ISSUE THREAD

**Issue by katosh** [satijalab/azimuth#133]
I hope this is the right place to ask, since the `bonemarrowref` is the human bone marrow reference dataset of Azimuth, listed here: https://azimuth.hubmapconsortium.org

I wanted to inspect the gene expression data of the dataset but the respective count matrix seems to be empty:
```R
suppressPackageStartupMessages(library(Seurat))

options(timeout = 600)
pbmc <- readRDS(url('https://zenodo.org/record/5521512/files/ref.Rds'))
GetAssayData(object = pbmc, slot = "counts")
```
returns
```
<0 x 0 matrix>
```
Is this intended or is there another way to access the expression data of the reference dataset?

Thank you!

**Comment by AustinHartman** [comment]
Hi @katosh, the Azimuth references don't contain the raw gene expression information (as you've noticed) since it's not required for mapping and cell type annotation and keeps the object sizes small. I'll share a Seurat object with you containing the gene expression which is otherwise identical to `bonemarrowref`.

**Comment by katosh** [comment]
Hi @AustinHartman, that is great! I really like the dataset and am excited to try out my cell-state-density estimation on it. Thank you so much!

**Comment by NoemieL** [comment]
Hi @AustinHartman,
I would be also interested by looking at the gene expression data of your bone marrow reference used by Azimuth.
Could you please make the seurat object publicly available? or share it using another way?

Thank you!
