### ISSUE TITLE
ConvertEnsembleToSymbol not found in Azimuth

### ISSUE THREAD

**Issue by ChristineHOconnor** [satijalab/azimuth#145]
I am following this tutorial (https://satijalab.org/seurat/articles/seurat5_bpcells_interaction_vignette.html) to load data from one hd5 file. The 'ConvertEnsembleToSymbol' function errors out. 

Code below (as far as I can tell the hd5 and data matrices are read in correctly): 
`library(BPCells)
library(Seurat)
library(SeuratObject)
library(SeuratDisk)
library(Azimuth)
options(Seurat.object.assay.version = "v5")

OU_count.data <- open_matrix_10x_hdf5(path = paste0(my_data_dir,"/filtered_feature_bc_matrix.h5"))
write_matrix_dir(mat = OU_count.data, dir = "matrix_dir/OU_counts_mat", overwrite = TRUE)
OU_count.mat <- open_matrix_dir(dir = "matrix_dir/OU_counts_mat")
OU_count.mat <- Azimuth::ConvertEnsembleToSymbol(mat = OU_count.mat, species = "mouse")
Error: 'ConvertEnsembleToSymbol' is not an exported object from 'namespace:Azimuth'

# also tried the command this way: 
OU_count.mat <- ConvertEnsembleToSymbol(mat = OU_count.mat, species = "mouse")
Error in ConvertEnsembleToSymbol(mat = OU_count.mat, species = "mouse") : 
  could not find function "ConvertEnsembleToSymbol"
` 

I am running R 4.2.2 on a university supercomputer system

**Comment by AustinHartman** [comment]
@ChristineHOconnor since the `ConvertEnsembleToSymbol` gene is not currently exported from the seurat5 branch of Azimuth, use three colons rather than two access the function:
`Azimuth:::ConvertEnsembleToSymbol(mat = OU_count.mat, species = "mouse")`

**Comment by ChristineHOconnor** [comment]
That option also errors out for me

`OU_count.mat <- Azimuth:::ConvertEnsembleToSymbol(mat = OU_count.mat, species = "mouse")
Error: object 'ConvertEnsembleToSymbol' not found`

**Comment by PerkyTussellop** [comment]
Also having this problem

**Comment by plrlhb12** [comment]
having the same issue in Feb 2024

**Comment by fingeram** [comment]
Hi, has there been any updates? Having the same issue with Seurat v4 and Azimuth v0.4.4 (June 2024)

**Comment by rhlgyb** [comment]
Hey,

I just visited the Azimuth github page and scooped up the code for this function.
Just manually run this code for the function to work.

Here it is :


ConvertEnsembleToSymbol <- function(
    mat,
    species = c('human', 'mouse')
) {
  species <- match.arg(arg = species)
  if (species == 'human') {
    database <- 'hsapiens_gene_ensembl'
    symbol <- 'hgnc_symbol'

  } else if (species == 'mouse') {
    database <- 'mmusculus_gene_ensembl'
    symbol <- 'mgi_symbol'

  } else {
    stop('species name not found')
  }

  library("biomaRt")
  library("dplyr")

  name_df <- data.frame(gene_id = c(rownames(mat)))
  name_df$orig.id <- name_df$gene_id
  #make this a character, otherwise it will throw errors with left_join
  name_df$gene_id <- as.character(name_df$gene_id)
  #in case it's gencode, this mostly works
  #if ensembl, will leave it alone
  name_df$gene_id <- sub("[.][0-9]*","",name_df$gene_id)
  mart <- useDataset(dataset = database, useMart("ensembl"))
  genes <-  name_df$gene_id
  gene_IDs <- getBM(filters= "ensembl_gene_id",
                    attributes= c("ensembl_gene_id", symbol),
                    values = genes,
                    mart= mart)
  gene.df <- left_join(name_df, gene_IDs, by = c("gene_id"="ensembl_gene_id"))
  rownames(gene.df) <- make.unique(gene.df$orig.id)
  gene.df <- gene.df[rownames(mat),]
  gene.df <-gene.df[gene.df[,symbol] != '',]
  gene.df <- gene.df[ !is.na(gene.df$orig.id),]
  mat.filter <- mat[gene.df$orig.id,]
  rownames(mat.filter) <- make.unique(gene.df[,symbol])
  return(mat.filter)
}


Best,

RL
