### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by ollieeknight** [satijalab/azimuth#159]
Heya, 

After running this line:
```
alldata <- RunAzimuth(alldata, reference = 'pbmcref', assay = 'RNA', verbose = F)
```

I get this error.
```
Error in curl::curl_fetch_memory(url, handle = handle) : SSL peer certificate or SSH remote key was not OK: [seurat.nygenome.org] SSL certificate problem: certificate has expired
```

Any suggestions?

**Comment by bobermayer** [comment]
had the same problem. you should be able download the objects yourself from zenodo (using `wget --no-check-certificate` or similar) and then provide the local path to Azimuth?

**Comment by ivokwee** [comment]
Same error here. Would appreciate a solution.

**Comment by ivokwee** [comment]
For those interested. I made a fork that has the `homologs.rds` inside the package, and doesn't need to download it, here `https://github.com/bigomics/azimuth`. But you would still need to download the reference files from https://azimuth.hubmapconsortium.org/references/  (Zenodo link). Put the `ref.Rds` and `idx.annoy`  in a folder called e.g. `my-pbmcref` and call `RunAzimuth(pbmcsca, reference = "./my-pbmcref")`.

**Comment by mlbendall** [comment]
Thanks @ivokwee! You can globally set curl to ignore certificate errors with `httr::set_config`. Together with the patch from @ivokwee you should not have to download the refs separately. Run this before you call `RunAzimuth`:

```
# Install patch
remotes::install_github('bigomics/azimuth', ref='master')

# Load library
library(Azimuth)

# Configure curl to ignore the expired certificate
httr::set_config(httr::config(ssl_verifypeer = 0L))

# Uses packaged homologs.rds and downloads refs from URL:
RunAzimuth(pbmcsca, reference="pbmcref")
```

NOTE: Changing curl/httr configuration seems to enable download of the references, but not `homologs.rds`. So I had to use the @ivokwee patch plus `httr::set_config(httr::config(ssl_verifypeer = 0L))` to get it to work, I could not get it to work with the upstream (satijalab) version. I suspect this is because `ConvertGeneNames` opens `homologs.rds` using `readRDS` - which is not using curl - and thus this still fails with the expired cert. If anyone knows how to configure `readRDS` to use `libcurl` globally, that would probably fix it.

**Comment by mlbendall** [comment]
Found it!

Before running `RunAzimuth`, set the `url.method` option to `libcurl` and then tell `curl` to use insecure mode. This works with the upstream version ('satijalab/azimuth', ref='master')

```
options(url.method='libcurl')
httr::set_config(httr::config(ssl_verifypeer = 0L))
RunAzimuth(...)
```
HTH

**Comment by AustinHartman** [comment]
The certificate has been updated, so `RunAzimuth` should work  again without needing to tell curl to ignore certificate errors.
