### ISSUE TITLE
do.correct.umi set to FALSE by default

### ISSUE THREAD

**Issue by sinanassiri** [satijalab/azimuth#61]
Dear Azimuth team,

Thanks for this awesome tool! Looking at the template R code that the online app generates after each run, it appears that the app runs SCTransform on input query with **do.correct.umi** set to **FALSE**. Can you please confirm that this is by design, and shed light on any theoretical or pragmatic reasons behind this choice?

[azimuth_analysis.txt](https://github.com/satijalab/azimuth/files/6565380/azimuth_analysis.txt)

Many thanks,
Sina

**Comment by andrewwbutler** [comment]
Hi Sina,

Yes, this is the intended behavior. While `SCTransform` is able to return corrected UMI counts, doing so adds some computational overhead and these corrected counts are not used in the mapping procedure (we're using the Pearson residuals). Since this is not an interactive analysis at the command line (where you might want to explore corrected counts for example), we opted to turn off any unnecessary/unused calculations in the commands being run in Azimuth.
